---
- name: grab agent jar
  command: wget http://jenkins.fastfeedback.rocks/jnlpJars/agent.jar
- name: Connect to master
  command: java -jar agent.jar -jnlpUrl http://jenkins.fastfeedback.rocks/computer/slave-{{agent_number}}/slave-agent.jnlp
- file:
    path: /home/jenkins
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: u+rwx,g+rwx
